name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: wrapper
          arguments: build curseforge
          env:
            CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/